eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://10.43.100.223:8761/eureka}
    # To report to Eureka when this service is up discovery-service
    registerWithEureka: true
  instance:
    ip-address: 10.43.101.44
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

firebase:
  type: 'service_account'
  project-id: 'allconnected-qa'
  private-key: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC5nGy9nd+R3I/0\ni7o+rSSJNHZcmLRNHbv51ncey/ylYKK4RrPoQtVTuFRGYiETbba7kgxiVPQ3i4eo\nuIh69lkka95BqAx8Mdv7zsiTSPZicPJPxaHBJId4cejgBq/YrUuBIFptjYBXl1kk\n7zvnd3t6D6KfaXrXPWZUsktFIAzKadyyzDW3cVCI92fhyEl5LVyVkTVK6KmjBXx3\nut7vGsaDZT8HkPOiVQto1YxoGJq0STtMDITG/2vAiV7wmmB0YEj4puC3lSF2/0f8\nP0J4vxTUiXsAiunJMcBZy2yiEMnmoVKgV5BKGDIPfih+HaThafswOP7YJwmibmMA\nbrrTVXZJAgMBAAECggEAA7+UdJnZF32ATLx7pONjPwAXudP9pCcLEkcR/cW50u8q\nKhWHcZPT8g5haVB3AYjwLUaMSHoVun9vXGlpnC4Ya8Nf6CyIIAPzwNiStWK+Uwub\n4R+JHjjqIXUPcmLAL1yEj1WDbf3zDxHH45aPO6Puku745kY/jFQ5mlFFct5sU7QZ\nyjSs4ni+g+bmSw84jHBM1tsaJqOejLSM7JQ71YXFMZeWPBzjkl78+OAE7RAzyUa7\nzleBf5BdfcdPdWcVUvLAm5DBSJKPz3Zjdcy1mbP77/YY89mqhsDfllRMQpSA9XfE\nCNVCLdevcQEm0HoYwT6kaJ1A9kJKlds9lAJg13h7OQKBgQDdc3eWjb9MH8YYK1+F\nhu9ldKyakjTPNZ5RMByxN6jNcRxgk6/q58VqIU+QpdepjBD9rMpMuClaI9xvxKb9\nBqy0fdkDL5RVncZo211lfy41iIzp+egEBif1g2pQG+dso43IJCghYeYr1KIpjTMR\n1PHjCDlTAGWgtv7+WrY2C00R3QKBgQDWkYsmiHMPNusPTzalpOaUWqRirYc7XjMc\nv2pCp17g63LHfjQTOF+YBXhJ4xyCnjS+PHRAKxpWca0ttDYsZH+7GoEar/nCROwY\nou3HOzfFrakF3ZtgszJYlHFwTSV8/U14xHhaSZyk5lBgf/jwmeJBf/nzT7pIff1I\nvt/o6KjNXQKBgQDTCyzIDTRnHszR0dwJy+uwO74W3Ql5A/dqFjjx50J277oEjBsV\n+mXYXACQsIxUJ4k1yItPDB9UqWJ2Heqqrsa+iETd1WU/JsqkuZJLnSXznLv2a9Ti\nqN9CCkiyKbWmgkQnndWk4sDRuqYEhW1LLC6NmBPRd0pjHKLs0pRd8u0y/QKBgCdT\nzdlmMRCc1ECeGDoMG2cdpfugKqUrAttGCkflPXKkNQlzjD/pmTvX5NBGHDekn64u\njnAkdlNZypAR88v3L6IvnXIyxuhgkZWCZ2qY5AQLbGtyzsPOlG+/5Xrb6P8bvlNg\nT17dFyTyQdEuI4aV7e5rcniyKEaZMQ9gTNH3stjRAoGBALh/OBA/Dxm15N2hzANv\nulZOEPLHn+Ixh2dkzu/noZrWMuBVLRYGElDmXDVVxc6h3wMVxwxoMLXx+vuAJzJB\ncqWVy6KGRGgr7wU/3ngjqM/iwU1mMq6vuuVrjXLwpb3vim1gbL23xsNCABj5NNUL\nEalC7FlVU7ovbH1UtTQnM1+3\n-----END PRIVATE KEY-----\n"
  private-key-id: '440a406b0d2a19685344962cf987de799db184e2'
  client-email: 'firebase-adminsdk-wa1w6@allconnected-qa.iam.gserviceaccount.com'
  client-id: '110885487469768285996'
  auth-uri: https://accounts.google.com/o/oauth2/auth
  token-uri: https://oauth2.googleapis.com/token
  auth-provider-x509-cert-url: https://www.googleapis.com/oauth2/v1/certs
  client-x509-cert-url: 'https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-wa1w6%40allconnected-qa.iam.gserviceaccount.com'
  universe-domain: googleapis.com