server:
  port: 9099

spring:
  application:
    name: metricas-service

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
